
import "./globals.css";
import { FoodProvider } from "./context";

export const metadata = {
  title: "NPC",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={``}>
         <FoodProvider>
          {children}
         </FoodProvider>
      </body>
    </html>
  );
}
